import Navbar from '@/Components/Navbar'
 import './globals.css'
import { Inter } from 'next/font/google'
import MenuBar from '@/Components/MenuBar'
import About from '@/Components/About'
import Head from "next/head";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "HDK's Creative Kaleidoscope: A Fusion of Art and Design",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
        <link rel="shortcut icon" href="/fab.jpg" />
      </Head>
      <body className={`${inter.className} bg-white`}>
     
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
